INSERT INTO States (name, acronym, countryID)
VALUES ('Alabama', 'AL', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Alaska', 'AK', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Arizona', 'AZ', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Arkansas', 'AR', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('California', 'CA', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Colorado', 'CO', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Connecticut', 'CT', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Delaware', 'DE', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Florida', 'FL', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Georgia', 'GA', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Hawaii', 'HI', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Idaho', 'ID', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Illinois', 'IL', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Indiana', 'IN', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Iowa', 'IA', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Kansas', 'KS', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Kentucky', 'KY', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Louisiana', 'LA', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Maine', 'ME', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Maryland', 'MD', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Massachusetts', 'MA', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Michigan', 'MI', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Minnesota', 'MN', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Mississippi', 'MS', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Missouri', 'MO', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Montana', 'MT', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Nebraska', 'NE', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Nevada', 'NV', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('New Hampshire', 'NH', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('New Jersey', 'NJ', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('New Mexico', 'NM', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('New York', 'NY', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('North Carolina', 'NC', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('North Dakota', 'ND', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Ohio', 'OH', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Oklahoma', 'OK', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Oregon', 'OR', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Pennsylvania', 'PA', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Rhode Island', 'RI', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('South Carolina', 'SC', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('South Dakota', 'SD', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Tennessee', 'TN', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Texas', 'TX', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Utah', 'UT', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Vermont', 'VT', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Virginia', 'VA', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Washington', 'WA', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('West Virginia', 'WV', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Wisconsin', 'WI', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america')),
       ('Wyoming', 'WY', (SELECT ID FROM Countries WHERE LOWER(name) LIKE 'united states of america'));