export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

function Home() {

    return (
        <div>
            <h1>Home</h1>
        </div>
    );

}

export default Home;